### ISSUE TITLE
uninitialized constant FileShare::Engine

### ISSUE THREAD

**Issue by ghost** [jlapier/Rails-CMS-Wiki-Forum#18]
jan@grayskull ~/dev/Rails-CMS-Wiki-Forum (git)-[master] % rake db:create
jan@grayskull ~/dev/Rails-CMS-Wiki-Forum (git)-[master] % rake db:migrate
==  CreateUsers: migrating ====================================================
-- create_table(:users)
   -> 0.0047s
-- add_index(:users, :login)
   -> 0.0004s
-- add_index(:users, :persistence_token)
   -> 0.0005s
-- add_index(:users, :email)
   -> 0.0006s
-- add_index(:users, :perishable_token)
   -> 0.0006s
-- add_index(:users, :last_request_at)
   -> 0.0007s
==  CreateUsers: migrated (0.0078s) ===========================================

==  CreateSessions: migrating =================================================
-- create_table(:sessions)
   -> 0.0024s
-- add_index(:sessions, :session_id)
   -> 0.0011s
-- add_index(:sessions, :updated_at)
   -> 0.0009s
==  CreateSessions: migrated (0.0050s) ========================================

==  CreateForums: migrating ===================================================
-- create_table(:forums)
   -> 0.0028s
==  CreateForums: migrated (0.0030s) ==========================================

==  CreateMessagePosts: migrating =============================================
-- create_table(:message_posts)
   -> 0.0012s
-- add_index(:message_posts, ["created_at"], {:name=>"index_messages_on_created_at"})
   -> 0.0003s
-- add_index(:message_posts, ["forum_id"], {:name=>"index_messages_on_forum_id"})
   -> 0.0007s
-- add_index(:message_posts, ["parent_id"], {:name=>"index_messages_on_parent_id"})
   -> 0.0008s
-- add_index(:message_posts, ["thread_id"], {:name=>"index_messages_on_thread_id"})
   -> 0.0010s
-- add_index(:message_posts, ["to_user_id"], {:name=>"index_messages_on_to_user_id"})
   -> 0.0009s
-- add_index(:message_posts, ["user_id"], {:name=>"index_messages_on_user_id"})
   -> 0.0008s
==  CreateMessagePosts: migrated (0.0065s) ====================================

==  CreateWikiPages: migrating ================================================
-- create_table("wiki_pages", {:force=>true})
   -> 0.0011s
-- add_index("wiki_pages", ["modifying_user_id"], {:name=>"index_wiki_pages_on_modifying_user_id"})
   -> 0.0003s
-- add_index("wiki_pages", ["url_title"], {:name=>"index_wiki_pages_on_url_title"})
   -> 0.0004s
==  CreateWikiPages: migrated (0.0044s) =======================================

==  CreateWikiTags: migrating =================================================
-- create_table("wiki_tags", {:force=>true})
   -> 0.0007s
-- add_index("wiki_tags", ["name"], {:name=>"index_wiki_tags_on_name"})
   -> 0.0005s
-- create_table("wiki_pages_wiki_tags", {:id=>false, :force=>true})
   -> 0.0006s
-- add_index("wiki_pages_wiki_tags", ["wiki_page_id"])
   -> 0.0004s
-- add_index("wiki_pages_wiki_tags", ["wiki_tag_id"])
   -> 0.0005s
==  CreateWikiTags: migrated (0.0030s) ========================================

==  CreateWikiComments: migrating =============================================
-- create_table("wiki_comments", {:force=>true})
   -> 0.0014s
-- add_index("wiki_comments", ["wiki_page_id"], {:name=>"index_wiki_comments_on_wiki_page_id"})
   -> 0.0004s
==  CreateWikiComments: migrated (0.0021s) ====================================

==  CreateContentPages: migrating =============================================
-- create_table(:content_pages)
   -> 0.0013s
==  CreateContentPages: migrated (0.0015s) ====================================

==  CreateCategories: migrating ===============================================
-- create_table(:categories)
   -> 0.0009s
-- create_table("categories_content_pages", {:id=>false, :force=>true})
   -> 0.0007s
-- add_index("categories_content_pages", ["content_page_id"])
   -> 0.0004s
-- add_index("categories_content_pages", ["category_id"])
   -> 0.0006s
==  CreateCategories: migrated (0.0030s) ======================================

==  CreateSiteSettings: migrating =============================================
-- create_table(:site_settings)
   -> 0.0012s
==  CreateSiteSettings: migrated (0.0013s) ====================================

==  CreateUserGroups: migrating ===============================================
-- create_table(:user_groups)
   -> 0.0015s
-- create_table(:user_groups_users, {:id=>false})
   -> 0.0004s
-- add_index(:user_groups_users, :user_id)
   -> 0.0004s
-- add_index(:user_groups_users, :user_group_id)
   -> 0.0005s
==  CreateUserGroups: migrated (0.0031s) ======================================

==  AddStageToContentPages: migrating =========================================
-- add_column(:content_pages, :is_preview_only, :boolean)
   -> 0.0014s
==  AddStageToContentPages: migrated (0.0017s) ================================

==  AddStartedEditsToContentPages: migrating ==================================
-- add_column(:content_pages, :started_editing_at, :datetime)
   -> 0.0010s
-- add_column(:content_pages, :editing_user_id, :integer)
   -> 0.0006s
-- add_column(:content_pages, :publish_on, :date)
   -> 0.0006s
==  AddStartedEditsToContentPages: migrated (0.0026s) =========================

==  AddAboutWikiToComments: migrating =========================================
-- add_column(:wiki_comments, :about_wiki_page_id, :integer)
   -> 0.0009s
==  AddAboutWikiToComments: migrated (0.0010s) ================================

==  AddStartedEditsToWikiPages: migrating =====================================
-- add_column(:wiki_pages, :started_editing_at, :datetime)
   -> 0.0010s
-- add_column(:wiki_pages, :editing_user_id, :integer)
   -> 0.0007s
-- add_column(:wiki_page_versions, :started_editing_at, :datetime)
   -> 0.0007s
-- add_column(:wiki_page_versions, :editing_user_id, :integer)
   -> 0.0007s
==  AddStartedEditsToWikiPages: migrated (0.0036s) ============================

==  CreateWikis: migrating ====================================================
-- create_table(:wikis)
   -> 0.0018s
==  CreateWikis: migrated (0.0020s) ===========================================

==  ChangeSpecialInUserGroups: migrating ======================================
-- change_column(:user_groups, :special, :text)
   -> 0.0095s
==  ChangeSpecialInUserGroups: migrated (0.0097s) =============================

==  AddWikiIdToWikiPages: migrating ===========================================
-- add_column(:wiki_pages, :wiki_id, :integer)
   -> 0.0017s
-- add_index(:wiki_pages, :wiki_id)
   -> 0.0022s
-- add_column(:wiki_page_versions, :wiki_id, :integer)
   -> 0.0012s
-- add_index(:wiki_page_versions, :wiki_id)
   -> 0.0016s
-- add_column(:wiki_comments, :wiki_id, :integer)
   -> 0.0012s
-- add_index(:wiki_comments, :wiki_id)
   -> 0.0016s
==  AddWikiIdToWikiPages: migrated (0.0107s) ==================================

==  AddWikiToTags: migrating ==================================================
-- add_column(:wiki_tags, :wiki_id, :integer)
   -> 0.0013s
==  AddWikiToTags: migrated (0.0015s) =========================================

==  AddReqGroupsToUsers: migrating ============================================
-- add_column(:users, :requested_user_group_ids, :string)
   -> 0.0018s
==  AddReqGroupsToUsers: migrated (0.0020s) ===================================

==  EventCalendarSchemaAfterMakeEventsRevisable: migrating ====================
-- create_table("event_calendar_attendees", {:force=>true})
   -> 0.0030s
-- create_table("event_calendar_events", {:force=>true})
   -> 0.0017s
==  EventCalendarSchemaAfterMakeEventsRevisable: migrated (0.0050s) ===========

==  FileShareSchemaAfterCreateFileAttachments: migrating ======================
-- create_table("file_share_file_attachments", {:force=>true})
   -> 0.0012s
-- add_index("file_share_file_attachments", ["attachable_id"], {:name=>"index_file_share_file_attachments_on_attachable_id"})
   -> 0.0004s
==  FileShareSchemaAfterCreateFileAttachments: migrated (0.0018s) =============

==  FileShareSeed: migrating ==================================================
rake aborted!
An error has occurred, this and all later migrations canceled:

uninitialized constant FileShare::Engine

Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by inertialbit** [comment]
Try using schema:load and let us know if the problem persists. Generally it is less error prone than db:migrate when installing for the first time.

```
rake db:schema:load
```

**Comment by dcvezzani** [comment]
I have the same problem.

If I do run rake db:schema:load as suggested and then fire up my server, I get this:

```
ActiveRecord::StatementInvalid (PG::Error: ERROR:  relation "site_settings" does not exist
LINE 1: SELECT  "site_settings".* FROM "site_settings" WHERE "site_s...
                                       ^
: SELECT  "site_settings".* FROM "site_settings" WHERE "site_settings"."setting_name" = 'theme layout' LIMIT 1):
  app/models/site_setting.rb:9:in `read_setting'
  app/models/site_setting.rb:64:in `read_or_write_default_setting'
  app/controllers/application_controller.rb:177:in `get_layout'

Rendered /Users/davidvezzani/.rvm/gems/ruby-1.9.2-p180/gems/actionpack-3.0.10/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.7ms)
Rendered /Users/davidvezzani/.rvm/gems/ruby-1.9.2-p180/gems/actionpack-3.0.10/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (4.6ms)
Rendered /Users/davidvezzani/.rvm/gems/ruby-1.9.2-p180/gems/actionpack-3.0.10/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (12.3ms)
```

'site_settings' wasn't in db/schema.rb, so it didn't get generated.  More importantly, there are references to FileShare::Engine in other parts of the code:

```
find . -exec grep -l FileShare {} \;
./app/controllers/application_controller.rb
./app/helpers/file_share/application_helper.rb
./db/migrate/20101202170830_file_share_schema_after_create_file_attachments.rb
./db/migrate/20101202170831_file_share_seed.rb
./lib/tasks/file_share.rake
./log/development.log
```

I'm not sure at this point how vital FileShare is to the app, but I'm going to guard the migration in the same way 'file_share.rake' does:

```
if defined? FileShare::Engine
  ...
end
```
